# Generated by Django 4.1 on 2025-07-10 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode_barang', models.CharField(max_length=30, unique=True)),
                ('jumlah', models.PositiveIntegerField()),
                ('lokasi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peminjam', models.CharField(max_length=100)),
                ('tanggal_pinjam', models.DateField(auto_now_add=True)),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('surat_permohonan', models.FileField(upload_to='surat_permohonan/')),
                ('status', models.CharField(choices=[('Dipinjam', 'Dipinjam'), ('Dikembalikan', 'Dikembalikan')], default='Dipinjam', max_length=20)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.barang')),
            ],
        ),
    ]
